In [1]:
import numpy as np

In [2]:
input_image = np.load("./data/image_65.npy")
dense_weights = np.load("./data/dense_weights.npy")
dense_biases = np.load("./data/dense_biases.npy")
dense_biases = dense_biases.reshape(-1,1)

dense_1_weights = np.load("./data/dense_1_weights.npy")
dense_1_biases = np.load("./data/dense_1_biases.npy")
dense_1_biases = dense_1_biases.reshape(-1,1)

In [3]:
dense_weights.shape

(784, 32)

In [4]:
input_image.shape

(784, 1)

In [30]:
input_image

array([[0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.   

In [5]:
dense_biases.shape

(32, 1)

In [6]:
l1 = np.matmul(dense_weights.transpose(), input_image)

In [7]:
l1

array([[ 2.7293727 ],
       [-0.9313587 ],
       [ 1.1676316 ],
       [ 2.8684986 ],
       [ 0.19651142],
       [-3.587397  ],
       [ 2.01474   ],
       [-3.2380881 ],
       [-1.5213758 ],
       [-5.436726  ],
       [-1.9560302 ],
       [-0.42414534],
       [ 3.2262049 ],
       [-0.5992355 ],
       [-0.8107381 ],
       [ 1.201575  ],
       [ 4.1837897 ],
       [ 1.6659362 ],
       [ 3.0075839 ],
       [ 2.0553336 ],
       [ 4.528326  ],
       [ 4.4232473 ],
       [-1.8737683 ],
       [-0.37545434],
       [-1.430711  ],
       [ 0.8473378 ],
       [-1.208431  ],
       [ 2.2449214 ],
       [ 1.2995405 ],
       [ 4.451985  ],
       [ 1.6272404 ],
       [-6.5767417 ]], dtype=float32)

In [8]:
b1 = (l1+dense_biases)
b1

array([[ 2.7031577 ],
       [-0.77147985],
       [ 1.0256499 ],
       [ 3.0645266 ],
       [ 0.28249195],
       [-3.6182792 ],
       [ 2.0511782 ],
       [-3.3319757 ],
       [-1.6909789 ],
       [-5.333047  ],
       [-2.1512473 ],
       [-0.3674449 ],
       [ 3.479577  ],
       [-0.503815  ],
       [-0.6811953 ],
       [ 1.1322763 ],
       [ 4.334353  ],
       [ 1.8195937 ],
       [ 3.1125522 ],
       [ 2.1701686 ],
       [ 4.5149164 ],
       [ 4.3959703 ],
       [-1.775066  ],
       [-0.2324662 ],
       [-1.379553  ],
       [ 0.6839734 ],
       [-1.2923486 ],
       [ 2.2864451 ],
       [ 1.367835  ],
       [ 4.415979  ],
       [ 1.5865097 ],
       [-6.284305  ]], dtype=float32)

In [9]:
b1_relu = (np.abs(b1)+b1)/2
b1_relu

array([[2.7031577 ],
       [0.        ],
       [1.0256499 ],
       [3.0645266 ],
       [0.28249195],
       [0.        ],
       [2.0511782 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [3.479577  ],
       [0.        ],
       [0.        ],
       [1.1322763 ],
       [4.334353  ],
       [1.8195937 ],
       [3.1125522 ],
       [2.1701686 ],
       [4.5149164 ],
       [4.3959703 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.6839734 ],
       [0.        ],
       [2.2864451 ],
       [1.367835  ],
       [4.415979  ],
       [1.5865097 ],
       [0.        ]], dtype=float32)

In [10]:
l2 = np.matmul(dense_1_weights.transpose(), b1_relu)
l2

array([[-0.9444927],
       [-4.2348657],
       [-1.8902569],
       [ 0.8297825],
       [-1.5688567],
       [ 6.4501   ],
       [-2.402465 ],
       [-2.7737036],
       [ 2.1492646],
       [-6.36913  ]], dtype=float32)

In [11]:
b2 = (l2+dense_1_biases)
b2

array([[-1.0759888],
       [-4.123219 ],
       [-1.9731127],
       [ 0.6457634],
       [-1.4876431],
       [ 6.7374544],
       [-2.372531 ],
       [-2.733576 ],
       [ 2.1288188],
       [-6.3753777]], dtype=float32)

In [12]:
import tensorflow as tf
b2_ = tf.nn.softmax(b2.squeeze())
b2_


<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([3.9896823e-04, 1.8947105e-05, 1.6267551e-04, 2.2319569e-03,
       2.6433766e-04, 9.8690099e-01, 1.0910816e-04, 7.6042685e-05,
       9.8348660e-03, 1.9927047e-06], dtype=float32)>

In [13]:
from scipy.special import softmax
softmax(b2)

array([[3.98968288e-04],
       [1.89471048e-05],
       [1.62675526e-04],
       [2.23195693e-03],
       [2.64337694e-04],
       [9.86900985e-01],
       [1.09108165e-04],
       [7.60426847e-05],
       [9.83486604e-03],
       [1.99270494e-06]], dtype=float32)

In [14]:
b2.argmax()

5

In [15]:
np.exp(b2)

array([[3.4096044e-01],
       [1.6192308e-02],
       [1.3902345e-01],
       [1.9074427e+00],
       [2.2590446e-01],
       [8.4341101e+02],
       [9.3244426e-02],
       [6.4986482e-02],
       [8.4049330e+00],
       [1.7029765e-03]], dtype=float32)

In [16]:
np.sum(np.exp(b2))

854.60535

In [17]:
w_mat = np.random.rand(7,5).astype(np.float32)
np.save("random_array",w_mat)
w_mat

array([[0.76026595, 0.36791432, 0.9445031 , 0.7283194 , 0.7160851 ],
       [0.08862857, 0.39960876, 0.11000559, 0.4933647 , 0.84496176],
       [0.84447175, 0.04103125, 0.18353052, 0.48500994, 0.22027114],
       [0.543797  , 0.8277258 , 0.51385236, 0.7472754 , 0.42964196],
       [0.73544925, 0.57853645, 0.79049534, 0.96133333, 0.4214276 ],
       [0.005819  , 0.61578184, 0.9414512 , 0.44219255, 0.69628876],
       [0.79232055, 0.66306967, 0.5100784 , 0.2741089 , 0.78423375]],
      dtype=float32)

In [18]:
i_vec = np.random.rand(5).astype(np.float32)
np.save("random_input",i_vec)
i_vec

array([0.03114411, 0.8691807 , 0.28055096, 0.16450857, 0.24428487],
      dtype=float32)

In [19]:
np.matmul(w_mat, i_vec)

array([0.9031866 , 0.66852874, 0.24705075, 1.1084294 , 1.0086278 ,
       1.0423691 , 0.98077613], dtype=float32)

In [20]:
np.dot(w_mat, i_vec)

array([0.9031866 , 0.66852874, 0.24705075, 1.1084294 , 1.0086278 ,
       1.0423691 , 0.98077613], dtype=float32)

In [21]:
i_mat = np.random.rand(5,3).astype(np.float32)
np.save("random_input_mat",i_mat)
i_mat

array([[0.46186587, 0.9467637 , 0.6773526 ],
       [0.2463912 , 0.3535584 , 0.42480564],
       [0.29815486, 0.2140467 , 0.18479149],
       [0.7126289 , 0.25286782, 0.6175266 ],
       [0.3188805 , 0.03862744, 0.65431637]], dtype=float32)

In [22]:
np.matmul(w_mat, i_mat)

array([[1.4707669 , 1.2638682 , 1.7640991 ],
       [0.79322106, 0.40613642, 1.107655  ],
       [0.8707352 , 0.98445815, 1.0669839 ],
       [1.2778478 , 1.123043  , 1.5575047 ],
       [1.5373741 , 1.3294148 , 1.7593967 ],
       [0.9722612 , 0.56345075, 1.1681601 ],
       [1.1268175 , 1.193361  , 1.5950208 ]], dtype=float32)

In [23]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])


In [24]:
c = np.matmul(a,b)

In [25]:
c

array([[19, 22],
       [43, 50]])

In [26]:
x = np.array([[0,1,2,3],
             [4,5,6,7],
             [8,9,10,11]])

y = np.array([[4,5,6,7,6],
             [0,1,2,3,1],
             [8,9,10,11,5],
             [0,1,2,3,9]])

In [27]:
z = np.matmul(x,y)
z

array([[ 16,  22,  28,  34,  38],
       [ 64,  86, 108, 130, 122],
       [112, 150, 188, 226, 206]])

In [28]:
x = np.random.rand(3,2).astype(np.float32)

In [29]:
x

array([[0.0700837 , 0.5778034 ],
       [0.7988258 , 0.0922296 ],
       [0.36721358, 0.16601987]], dtype=float32)